"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest

pytestmark = pytest.mark.skipif(
    shutil.which("scitex-dev") is None,
    reason="scitex-dev not installed — add `scitex-dev[cli-audit]` to [dev]",
)


def test_audit_all_for_scitex_context_returns_without_error():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    target_distribution = "scitex-context"

    # Act
    result = audit_all_for_package(target_distribution)

    # Assert
    assert result in (None, True, 0)
